name: esc_pos_utils_pro
description: This package is used to generate ESC/pos commands to print using Bluetooth, WiFi/Network, or USB printers.
version: 1.0.0
homepage: https://github.com/Karahan00/esc_pos_utils_pro

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0
  gbk_codec: ^0.4.0
  image: ^4.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  assets:
    - packages/esc_pos_utils_pro/resources/capabilities.json
